### ISSUE TITLE
Ambiguous occurrence ‘singleton

### ISSUE THREAD

**Issue by andrewufrank** [msakai/toysolver#79] opened 2022-07-25 09:52 UTC
compiling with `allow-newer` and ghc 9.0.2 (base 4.15.1) I encountered the following error: 

src/ToySolver/Data/LA.hs:302:43: error:
    Ambiguous occurrence ‘singleton’
    It could refer to
       either ‘Data.List.singleton’,
              imported from ‘Data.List’ at src/ToySolver/Data/LA.hs:70:1-16
              (and originally defined in ‘base-4.15.1.0:Data.OldList’)
           or ‘Data.Interval.singleton’,
              imported from ‘Data.Interval’ at src/ToySolver/Data/LA.hs:75:1-20

I assume this is easy to resolve! Thank you!

**Comment by msakai** [comment] 2022-07-26 13:49
The problem is already fixed on the `master` branch (#69). 
I'll release a new version to Hackage.

**Comment by msakai** [comment] 2022-07-26 23:41
I just released a new version `0.8.0` to Hackage.

**Comment by andrewufrank** [comment] 2022-08-20 21:00
Thank you!

**Closed** 2023-01-21 13:39 UTC
